# Generated by Django 5.1.6 on 2025-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="image_URL",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="referral_link",
            field=models.URLField(),
        ),
    ]
