# Generated by Django 5.1.6 on 2025-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="last_weighted",
            field=models.DateTimeField(
                blank=True, default="2024-04-01 05:34:05.086339"
            ),
            preserve_default=False,
        ),
    ]
