# Generated by Django 5.1.6 on 2025-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="booking",
            name="image_URL",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="referral_link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
