# Generated by Django 5.1.6 on 2025-07-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_island_title_alter_booking_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="description_element",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="type",
            name="header_element",
            field=models.TextField(blank=True),
        ),
    ]
