# Generated by Django 5.1.6 on 2025-04-01 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_booking_last_weighted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="last_weighted",
        ),
    ]
