# Generated by Django 5.1.6 on 2025-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_booking_image_url_alter_booking_referral_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
