# Generated by Django 5.1.6 on 2025-03-05 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_searchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("count", models.IntegerField(default=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.island"
                    ),
                ),
                ("results", models.ManyToManyField(to="core.booking")),
            ],
        ),
    ]
