# Generated by Django 5.1.6 on 2025-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_booking_last_weighted"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRandomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
