# Generated by Django 5.1.6 on 2025-07-20 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_type_description_element_type_header_element"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="type",
            name="description_element",
        ),
        migrations.RemoveField(
            model_name="type",
            name="header_element",
        ),
    ]
