# Generated by Django 5.1.6 on 2025-04-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_bookingrandomization"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_amount",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
