# Generated by Django 5.1.6 on 2025-07-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_type_description_element_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_element",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="header_element",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="island",
            name="description_element",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="island",
            name="header_element",
            field=models.TextField(blank=True),
        ),
    ]
