# Generated by Django 5.1.6 on 2025-04-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_booking_is_promo_booking_promo_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="modifed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
