# Generated by Django 5.1.6 on 2025-06-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="island",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
