# Generated by Django 5.1.6 on 2025-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_category_description_element_category_header_element_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description_element",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="island",
            name="description_element",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
