# Generated by Django 5.1.6 on 2025-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_island_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="island",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
