# Generated by Django 5.1.6 on 2025-04-10 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_type_modifed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="type",
            old_name="modifed",
            new_name="modified",
        ),
    ]
