# Generated by Django 5.1.6 on 2025-07-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_category_description_element_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description_element",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="category",
            name="header_element",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="island",
            name="description_element",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="island",
            name="header_element",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
