# Generated by Django 5.1.6 on 2025-04-12 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_modifed_type_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_verified",
        ),
    ]
