# Generated by Django 5.1.6 on 2025-03-05 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_searchquery_results"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="clicks",
        ),
        migrations.RemoveField(
            model_name="island",
            name="clicks",
        ),
        migrations.RemoveField(
            model_name="type",
            name="clicks",
        ),
    ]
