# Generated by Django 5.1.6 on 2025-07-21 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_category_description_element_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="island",
            name="description_element",
        ),
        migrations.RemoveField(
            model_name="island",
            name="header_element",
        ),
    ]
