# Generated by Django 5.1.6 on 2025-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_category_clicks_remove_island_clicks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisit",
            name="ref",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
