# Generated by Django 5.1.6 on 2025-04-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_booking_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="company_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="fh_id",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="image_URL",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="referral_link",
            field=models.TextField(),
        ),
    ]
