# Generated by Django 5.1.6 on 2025-04-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_booking_company_name_alter_booking_fh_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="fh_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
