# Generated by Django 5.1.6 on 2025-07-22 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_island_description_element_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description_element",
        ),
    ]
