# Generated by Django 5.1.6 on 2025-03-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_booking_clicks_category_clicks_island_clicks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.category",
            ),
        ),
    ]
