# Generated by Django 5.1.6 on 2025-04-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_booking_fh_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="image_URL",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="referral_link",
            field=models.URLField(),
        ),
    ]
