# Generated by Django 5.1.6 on 2025-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_category_description_element"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="image_mobile_URL",
            field=models.URLField(default="test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="header_element",
            field=models.CharField(max_length=60),
        ),
    ]
