# Generated by Django 5.1.6 on 2025-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_booking_image_url_alter_booking_referral_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="image_URL",
            field=models.URLField(default=""),
        ),
    ]
