# Generated by Django 5.1.6 on 2025-08-12 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_island_image_mobile_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="island",
            old_name="image_URL",
            new_name="hero_URL",
        ),
        migrations.RenameField(
            model_name="island",
            old_name="image_mobile_URL",
            new_name="hero_mobile_URL",
        ),
    ]
