# Generated by Django 5.1.6 on 2025-03-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_booking_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
    ]
