# Generated by Django 5.1.6 on 2025-04-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_island_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="island",
            name="image_URL",
            field=models.URLField(),
        ),
    ]
