# Generated by Django 5.1.6 on 2025-08-12 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_image_url_island_hero_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="island",
            old_name="title",
            new_name="name_title",
        ),
    ]
