# Generated by Django 5.1.6 on 2025-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_title_island_name_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="page_description",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="island",
            name="page_title",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
