# Generated by Django 5.1.6 on 2025-08-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_island_page_description_island_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="island",
            name="page_description",
            field=models.TextField(blank=True),
        ),
    ]
