# Generated by Django 5.1.6 on 2025-03-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_fareharbor_item_id_booking_fh_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
