# Generated by Django 5.1.6 on 2025-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_island_page_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="page_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="page_title",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
