# Generated by Django 5.1.6 on 2025-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_category_page_description_category_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="page_description",
            field=models.TextField(default="Page Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="page_title",
            field=models.CharField(default="Page Title", max_length=80),
        ),
        migrations.AlterField(
            model_name="island",
            name="page_description",
            field=models.TextField(default="Page Description"),
        ),
        migrations.AlterField(
            model_name="island",
            name="page_title",
            field=models.CharField(default="Page Title", max_length=80),
        ),
    ]
