# Generated by Django 5.1.6 on 2025-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_category_page_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="lg_featured_URL",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="island",
            name="lg_featured_company",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="island",
            name="sm_featured_URL",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="island",
            name="sm_featured_company",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
