# Generated by Django 5.1.6 on 2025-03-13 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_island_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="island",
            name="traffic",
        ),
    ]
