# Generated by Django 5.1.6 on 2025-08-12 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_island_lg_featured_url_island_lg_featured_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="header_element",
        ),
    ]
