# Generated by Django 5.1.6 on 2025-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_category_header_element"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="duration",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
