# Generated by Django 5.1.6 on 2025-08-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_booking_details_booking_duration_booking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company_rating",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="company_reviews",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
