# Generated by Django 5.1.6 on 2025-10-03 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_booking_company_rating_booking_company_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="company_rating",
        ),
        migrations.RemoveField(
            model_name="island",
            name="lg_featured_URL",
        ),
        migrations.RemoveField(
            model_name="island",
            name="lg_featured_company",
        ),
        migrations.RemoveField(
            model_name="island",
            name="sm_featured_URL",
        ),
        migrations.RemoveField(
            model_name="island",
            name="sm_featured_company",
        ),
    ]
