# Generated by Django 5.1.6 on 2025-08-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_booking_company_rating_booking_company_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="company_rating",
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
