# Generated by Django 5.1.6 on 2025-10-03 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_booking_company_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="island",
            old_name="page_description",
            new_name="island_page_description",
        ),
        migrations.RenameField(
            model_name="island",
            old_name="page_title",
            new_name="island_page_title",
        ),
    ]
