# Generated by Django 5.1.6 on 2025-10-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0023_rename_page_description_island_island_page_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="bookings_page_description",
            field=models.TextField(default="Page Description"),
        ),
        migrations.AddField(
            model_name="island",
            name="bookings_page_title",
            field=models.CharField(default="Page Title", max_length=80),
        ),
    ]
