# Generated by Django 5.1.6 on 2025-10-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_island_bookings_page_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="wp_category_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
