# Generated by Django 5.1.6 on 2025-12-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_island_wp_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
