# Generated by Django 5.1.6 on 2025-12-31 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_booking_company_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="company_rating",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="company_reviews",
        ),
    ]
