# Generated by Django 5.1.6 on 2025-12-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_remove_booking_company_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0.0, max_digits=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="company_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
