# Generated by Django 5.1.6 on 2026-01-02 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_booking_company_rating_booking_company_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="promo_amount",
        ),
    ]
