# Generated by Django 5.1.6 on 2026-01-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_booking_price_remove_booking_promo_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
