# Generated by Django 5.1.6 on 2026-01-02 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_booking_price_booking_promo_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="promo_amount",
        ),
    ]
