# Generated by Django 5.1 on 2025-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("fareharbor_item_id", models.IntegerField()),
                ("referral_link", models.URLField()),
                ("image_URL", models.URLField()),
                ("island", models.CharField(max_length=30)),
            ],
        ),
    ]
