# Generated by Django 5.1 on 2025-02-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="referral_link",
            field=models.URLField(max_length=500),
        ),
    ]
