# Generated by Django 5.1 on 2025-02-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_booking_referral_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
