# Generated by Django 5.1 on 2025-02-28 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_type_alter_booking_referral_link_alter_booking_title_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
    ]
