# Generated by Django 5.1 on 2025-02-28 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_category_categories"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
    ]
