# Generated by Django 5.1 on 2025-02-28 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_categories_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Island",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.type"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="island",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.island"
            ),
        ),
    ]
