# Generated by Django 5.1 on 2025-02-28 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_island_alter_booking_category_alter_booking_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="type",
        ),
    ]
