# Generated by Django 5.1 on 2025-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
