# Generated by Django 5.1.6 on 2025-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_sitevisit_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="clicks",
        ),
        migrations.AddField(
            model_name="category",
            name="clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="island",
            name="clicks",
            field=models.IntegerField(default=0),
        ),
    ]
