# Generated by Django 5.1.6 on 2025-03-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_category_is_popular"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="island",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="type",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
