# Generated by Django 5.1.6 on 2025-03-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_booking_views_category_views_island_views_type_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
