# Generated by Django 5.1.6 on 2025-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_booking_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="weight",
            field=models.IntegerField(default=2500),
        ),
    ]
