# Generated by Django 5.1.6 on 2025-03-06 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_clicks_category_traffic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="fareharbor_item_id",
            new_name="fh_id",
        ),
    ]
