# Generated by Django 5.1.6 on 2025-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_booking_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
