# Generated by Django 5.1.6 on 2025-03-04 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_visit"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visit",
            new_name="SiteVisit",
        ),
    ]
