# Generated by Django 5.1.6 on 2025-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_booking_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_varified",
            field=models.BooleanField(default=False),
        ),
    ]
