# Generated by Django 5.1.6 on 2025-03-11 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_booking_is_varified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="is_varified",
            new_name="is_verified",
        ),
    ]
