# Generated by Django 5.1.6 on 2025-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rename_is_varified_booking_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
